alias av='source venv/bin/activate'
alias c='clear'
alias cdiff='colordiff'
alias cs='calcurse'
alias dv='deactivate'
alias gc='git config credential.helper store'
alias ipy='ipython'
alias l='ls -la'
alias lg='lazygit'
alias ms='mailsync'
alias mt='neomutt'
alias r='echo $RANGER_LEVEL'
alias pu='python3 -m pudb'
alias ra='ranger'
# ra() {
	#if [ -z "$RANGER_LEVEL" ]
	#then
		#ranger
	#else
		#exit
	#fi
#}
alias s='neofetch'
alias g='onefetch'
alias sra='sudo -E ranger'
alias sudo='sudo -E'
alias vim='nvim'
alias gs='git config credential.helper store'
alias bat='sudo tlp bat'
alias ac='sudo tlp ac'
alias gy='git-yolo'
alias nb='newsboat -r'
alias nt="sh -c 'cd $(pwd); st' > /dev/null 2>&1 &"
alias ta='tmux a'
alias t='tmux'
alias lo='lsof -p $(fps) +w'
alias tf='conda activate tf115'
alias tfold='conda activate tf115'
alias pt='conda activate pt_py37'
alias ptold='conda activate pt_old'
alias mds='conda activate mindspore'
alias cac='conda activate'
alias cde='conda deactivate'
alias pad='conda activate paddle'
alias proxy='sudo -E nvim /etc/profile'
alias zsh='source ~/.zshrc'
alias vzsh='nvim ~/.zshrc'
alias path='nvim ~/zsh/path.zsh'
alias nv='nvidia-smi'
alias xm='sh ~/xmodmap.sh'
alias jn='jupyter notebook'
alias maix='sh ~/Downloads/maixpy/bin/maixpyide.sh'
alias kend='~/Downloads/KendryteIDE/KendryteIDE.sh'
alias obj='cd ~/Code/Projects/Object-detection/models/research/object_detection'
alias idea='sh ~/local_install/idea-IC-203.6682.168/bin/idea.sh'
